import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" data-theme="emerald">
			<body className={`${inter.className} pt-20`}>
				<Navbar />
				<div className="drawer">
					<input
						id="my-drawer"
						type="checkbox"
						className="drawer-toggle"
					/>
					<div className="drawer-content">{children}</div>
					<div className="drawer-side">
						<label
							htmlFor="my-drawer"
							aria-label="close sidebar"
							className="drawer-overlay"
						/>
						<ul className="menu bg-base-200 text-base-content min-h-full w-80 p-4">
							<li>
								<Link href={"#"}>Sidebar Item 1</Link>
							</li>
							<li>
								<Link href={"#"}>Sidebar Item 2</Link>
							</li>
						</ul>
					</div>
				</div>
			</body>
		</html>
	);
}
